### ISSUE TITLE
The plugin behaves incorrectly with tabs

### ISSUE THREAD

**Issue by lromanov** [kshetline/ligatures-limited-intellij#10]
Hi,
It seems the plugin behaves incorrectly with tabs (standard in golang):
![image](https://user-images.githubusercontent.com/4731590/103102868-374afa80-462f-11eb-83df-31c7cff1360b.png)
![image](https://user-images.githubusercontent.com/4731590/103102851-27331b00-462f-11eb-80a9-8a4c07128880.png)

**Comment by lromanov** [comment]
It seems the issue is that a text containing tabs spans on more columns in editor than the number of characters it has, so the (index, span) pair is determined incorrectly.

**Comment by kshetline** [comment]
Sorry I haven't had time to look into this yet, but I'll try to get on it next week.

**Comment by kshetline** [comment]
I've found the bug and fixed it. As soon as the updated plugin has been approved, it should be available for you.
